In [1]:

# Comment if you're not using colab
# from google.colab import drive
# drive.mount('/content/drive')

import tensorflow as tf

In [2]:
con1 = tf.constant([[3,4],[4,5]])
con2 = tf.constant(3.45)
con3 = tf.constant("Spartaa!!")
con4 = tf.constant(False)

In [3]:
print(con1,con2,con3,con4)

tf.Tensor(
[[3 4]
 [4 5]], shape=(2, 2), dtype=int32) tf.Tensor(3.45, shape=(), dtype=float32) tf.Tensor(b'Spartaa!!', shape=(), dtype=string) tf.Tensor(False, shape=(), dtype=bool)


In [6]:
Addition = tf.constant(50) + tf.constant(10)
Multiplication = tf.constant(20) * tf.constant(20)

In [7]:
print(Addition)

tf.Tensor(60, shape=(), dtype=int32)


In [8]:
Addition = tf.constant([1,2,3,4,5]) + tf.constant([5,4,3,2,1])
Multiplication = tf.constant([1,2,3,4,5]) * tf.constant([5,4,3,2,1])

In [9]:
print(Addition,Multiplication)

tf.Tensor([6 6 6 6 6], shape=(5,), dtype=int32) tf.Tensor([5 8 9 8 5], shape=(5,), dtype=int32)


In [10]:
str1 = tf.constant("I love")
str2 = tf.constant("TensorFlow")

In [12]:
print(str1+str2)

tf.Tensor(b'I loveTensorFlow', shape=(), dtype=string)


In [18]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()

In [19]:
str_name = tf.placeholder(tf.string)

In [20]:
name1 = "I am" + str_name

In [21]:
sess.run(name1,{str_name:" Sam"})

b'I am Sam'

In [26]:
# creating a placeholder
a = tf.placeholder(tf.float32, None)
  
# creating an operation
b = a + 10
  
# creating a session
with tf.Session() as session:
    
    # feeding data in the placeholder
    operation_res = session.run(b, feed_dict={a: [10, 20, 30, 40]})
    print("after executing the operation: " + str(operation_res))

after executing the operation: [20. 30. 40. 50.]
